### PR TITLE
Force git commit timestamp to be read as utc

### PR DESCRIPTION
**Pull request by OnGle**
Pending review, don't merge yet

### CODE REVIEW

**Comment by lamby** [comment]
Neat! I think we need to check (at least!):

* https://github.com/OnGle/verseek/blob/94338fa05be375d06f8235bcf995b82f37269f48/pylib/verseek.py#L223 will always use the `C` locale (for `%a` IIRC)

* https://github.com/OnGle/verseek/blob/94338fa05be375d06f8235bcf995b82f37269f48/pylib/verseek.py#L199 will always return the underlying value in the current timezone.

**Comment by OnGle** [comment]
- https://github.com/OnGle/verseek/blob/94338fa05be375d06f8235bcf995b82f37269f48/pylib/verseek.py#L223 I hadn't considered `%a`, I'll look into how best to replace that.

- https://github.com/OnGle/verseek/blob/94338fa05be375d06f8235bcf995b82f37269f48/pylib/verseek.py#L199 `git._cat_file`? Interesting, I'll have another look

Cheers for the feedback, much appreciated :)

**Comment by lamby** [comment]
@OnGle No problem. Feel to ping for another once-over :-)

**Comment by OnGle** [comment]
Date formatting Solutions
-------------------------------
As far as `%a` (and `%b` for that matter) it seems it does not use the C locale but rather whatever locale python uses, which (for me atleast) was undefined but acted like the C locale. 

So I see 3 possible solutions:

1. Using `locale.setlocale(locale.LC_TIME, '<locale identifier>')` will make strftime use formats for that locale. I havn't tested this thouroughly but it seems to work as expected on my system when setting it to `en_AU.UTF-8` `%x` shows dates formatted as `day/month/year` rather than `month/day/year`, and `zh_CN.UTF-8` changes `%a` and `%b` (although whether correctly or not I couldn't tell you, I don't know chinese). It also appears tkldev comes with `en_US.UTF-8` and iirc debian expects dates in changelogs to be localized to some english locale and `en_US.UTF-8` seems like a fine candidate to me. If my assumptions are correct and this is reliable, this would probably be the prefered solution IMO.

2. The `arrow` python library (packaged in debian) works as an extension to datetime and allows you to pass your preferred locale directly into the format function but is probably overkill if we can achieve the same ends using standard library modules.

3. We could manually determine the month and day names directly from the month and day numbers, however this seems error prone, unreliable and probably less readable. This to me seems like a last option if all else fails but included for completness

---
Since the first option seems like both the best and easiest option to me, I'll quickly make those changes, it wont take much time and I can remove it if needed, saves waiting more than necessary for communication across timezones.

**Comment by OnGle** [comment]
As far as git cat goes I followed it to https://github.com/turnkeylinux/turnkey-pylib/blob/c201a49424d86115921042c23d22104178a04760/pylib/git.py#L275 which ends up just executing `git cat-file commit <commit-id>` I attempted to reproduce timezone-dependant output but was unable, using `TZ="..." git cat-file ...`, `timedatectl set-timezone` and `dpkg-reconfigure tzdata` I get the same output. Am I missing something?

**Comment by lamby** [comment]
>  I attempted to reproduce timezone-dependant output but was unable, using TZ="..." git cat-file ..., timedatectl set-timezone and dpkg-reconfigure tzdata I get the same output. Am I missing something?

Probably not, it was much more of a "we need to check" rather than "we need to fix". :)

**Comment by JedMeister** [comment]
Hey @lamby & @OnGle 

Where is this one up to? Do we need to include any additional code? (I.e. what was mentioned in https://github.com/turnkeylinux/verseek/pull/3#issuecomment-377073407) or am I good to run some final tests on my end, then merge?

**Comment by lamby** [comment]
>  zh_CN.UTF-8 changes %a and %b

Probably means we should ensure the locale. Using the `C` locale is prefered over en_US; there is no guarantee the latter will be installed.

**Comment by OnGle** [comment]
@lamby that sounds reasonable, so long as LC_TIME formated as C locale will produce correct output for the changelog I'm not too fussed.

I'll make the change, if you have no other suggestions @lamby, then tomorrow perhaps @JedMeister you can build/test/merge :)

**Comment by OnGle** [comment]
I've added the change here, note that I've opted to just wrap the time formatting in the locale change just incase there are other unknown side effects but if necessary it's an easy change to apply the locale to the entire file.

**Comment by lamby** [comment]
* `LC_TIME` should be sufficient, yes.
* As a Python style thing, I would actually recommend making a quick context manager for this - it really neatly captures the idea of "set this, but unset it later" without the need to (for example) assign to `old_locale`. :)

**Comment by OnGle** [comment]
@lamby I actually did think of that but I was running a little low on time yesterday, I might do that now quickly. I agree it fits perfectly for what we're doing :)

**Comment by JedMeister** [comment]
Awesome work @OnGle! I have just completed testing and this (with #4 also applied) and it appears to work a treat! Reproducible packages, regardless of timezone setting! :clap: :clap: :clap: I feel really confident that we're all good to push on!

Are you happy with this (and #4) @lamby?

If so, I'll merge both ASAP and we're good to get @alonswartz to build all the stretch related packages! :tada: :champagne: :clinking_glasses:  

The very final test will be if the packages he builds match the shasums of ours. I can't see why they won't, but we'll double check to be sure. :smile: 

----

As something of an aside, unfortunately, the packaging changes required to make verseek itself reproducible appear to be incompatible for our jessie build infrastructure. :cry: 

However, seeing as the whole point is to build for stretch, IMO it is totally legitimate to skip that (reproducible jessie builds) and push forward!

Seeing as I'm still using jessie build infrastructure though, I figured it was "best practice" to build a jessie package to use for building reproducible stretch packages. (FWIW initial testing was done using a stretch package of verseek, installed to jessie via dpkg).

So to do that, I reset verseek back to pre-reproducible state and cherry picked the relevant commits from @OnGle. The jessie build of verseek with the relevant commits, is here: https://github.com/JedMeister/verseek/commits/jessie

I'm pretty sure that Alon is using a stretch based build env, so there may not be a ton of value in that. However, until we produce a v15.0 (stretch based) TKLDev, there may be some value...?

**Comment by lamby** [comment]
Yay for context managers :)

**Comment by JedMeister** [comment]
Ok. Everybody seems happy and my testing has been successful, so I'm going to merge this into master now. :smile: Yay!

**Pull request merged**
